/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants/{tenantSlug}/sesiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia sesion como administradora del centro. */
        post: operations["SesionesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantSlug}/servicios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogo de tratamientos del centro, paginado por cursor. */
        get: operations["ServiciosController_findAll"];
        put?: never;
        /** Da de alta un tratamiento. Solo la administradora del centro. */
        post: operations["ServiciosController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantSlug}/servicios/{servicioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Un tratamiento puntual. */
        get: operations["ServiciosController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edita un tratamiento. Es tambien la baja, con `{"activo": false}`. */
        patch: operations["ServiciosController_update"];
        trace?: never;
    };
    "/api/v1/tenants/{tenantSlug}/ventanas-atencion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Las franjas en que el centro toma turnos, con su capacidad. */
        get: operations["VentanasAtencionController_findAll"];
        /** Reemplaza la semana completa de franjas de atencion. */
        put: operations["VentanasAtencionController_replaceAll"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantSlug}/servicios/{servicioId}/disponibilidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Horarios de un dia para un tratamiento, con los cupos que quedan en cada uno. */
        get: operations["DisponibilidadController_find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantSlug}/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** La agenda del centro, paginada por cursor. Solo la administradora. */
        get: operations["ReservasController_findAll"];
        put?: never;
        /** Reserva un turno. Publico: la clienta no tiene cuenta, deja sus datos de contacto. */
        post: operations["ReservasController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantSlug}/reservas/{reservaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirma o cancela un turno. */
        patch: operations["ReservasController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorDto: {
            /**
             * @description Identificador de maquina del error. Es el que conviene usar para ramificar.
             * @example slot_full
             * @enum {string}
             */
            code: "validation_error" | "invalid_cursor" | "invalid_credentials" | "unauthenticated" | "invalid_token" | "wrong_tenant" | "tenant_not_found" | "servicio_not_found" | "reserva_not_found" | "servicio_name_taken" | "ventanas_superpuestas" | "slot_full" | "outside_business_hours" | "past_date" | "too_far_ahead" | "invalid_transition" | "high_contention";
            /**
             * @description Texto en espanol, listo para mostrarle a una persona.
             * @example Ese horario ya no tiene cupo. Elegi otro.
             */
            message: string;
        };
        CrearSesionDto: {
            /**
             * Format: email
             * @description Email de la persona administradora del centro.
             * @example admin@ejemplo.test
             */
            email: string;
            /** @description Su contrasena. */
            password: string;
        };
        UsuarioSesionDto: {
            id: string;
            nombre: string;
            /** @description Siempre `admin` en el MVP. */
            rol: string;
        };
        SesionDto: {
            /**
             * @description JWT para el header `Authorization: Bearer <token>`.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            usuario: components["schemas"]["UsuarioSesionDto"];
        };
        CursorPageDto: {
            data: Record<string, never>[];
            /**
             * @description Pasalo como `cursor` para pedir la pagina siguiente. null = era la ultima.
             * @example null
             */
            nextCursor: string | null;
        };
        ServicioDto: {
            /**
             * @description Precio total, en centavos. 1800000 son $18.000,00.
             * @example 1800000
             */
            precioCentavos: number;
            /**
             * @description Sena que se cobra al reservar, en centavos. Nunca mayor al precio.
             * @example 540000
             */
            senaCentavos: number;
            id: string;
            /** @description Nombre del tratamiento. Unico dentro del centro. */
            nombre: string;
            descripcion: string | null;
            /** @description Cuanto dura el turno. Define cuantos inicios de grilla entran en cada franja. */
            duracionMinutos: number;
            /** @description Si el tratamiento necesita una valoracion previa con el equipo. */
            requiereValoracion: boolean;
            /** @description Un servicio inactivo no se puede reservar. La baja es logica. */
            activo: boolean;
        };
        CreateServicioDto: {
            /** @description Nombre del tratamiento. Unico dentro del centro. */
            nombre: string;
            descripcion?: string;
            /**
             * @description Duracion del turno en minutos.
             *
             *     El minimo no es cosmetico: con 0, horaFin queda igual a horaInicio, el predicado de
             *     solape no matchea nada y el control de capacidad queda desactivado.
             */
            duracionMinutos: number;
            /** @description Precio total en centavos. */
            precioCentavos: number;
            /** @description Sena en centavos. El service valida ademas que no supere al precio. */
            senaCentavos: number;
            requiereValoracion?: boolean;
        };
        UpdateServicioDto: {
            /** @description Nombre del tratamiento. Unico dentro del centro. */
            nombre?: string;
            descripcion?: string;
            /**
             * @description Duracion del turno en minutos.
             *
             *     El minimo no es cosmetico: con 0, horaFin queda igual a horaInicio, el predicado de
             *     solape no matchea nada y el control de capacidad queda desactivado.
             */
            duracionMinutos?: number;
            /** @description Precio total en centavos. */
            precioCentavos?: number;
            /** @description Sena en centavos. El service valida ademas que no supere al precio. */
            senaCentavos?: number;
            requiereValoracion?: boolean;
            activo?: boolean;
        };
        VentanaAtencionDto: {
            /**
             * @description 1 lunes .. 7 domingo. Un dia sin franjas es un dia cerrado.
             * @example 1
             */
            diaSemana: number;
            /**
             * @description Hora de pared en que abre la franja, "HH:mm".
             * @example 09:00
             */
            horaInicio: string;
            /**
             * @description Minuto mas tardio en que un turno puede TERMINAR, no cuando se cierra la puerta.
             *     Con 13:30 un tratamiento de 45 minutos llega a empezar 12:45.
             * @example 13:30
             */
            horaFin: string;
            /**
             * @description Separacion entre inicios de la grilla, en minutos.
             * @example 45
             */
            intervaloMinutos: number;
            /**
             * @description Turnos simultaneos aceptados en esta franja. Mayor a 1 habilita el doble turno.
             * @example 1
             */
            capacidad: number;
        };
        VentanasAtencionDto: {
            data: components["schemas"]["VentanaAtencionDto"][];
        };
        ReplaceVentanasDto: {
            data: components["schemas"]["VentanaAtencionDto"][];
        };
        SlotDto: {
            /**
             * @description Hora de inicio, en hora de pared del centro.
             * @example 09:45
             */
            hora: string;
            /**
             * @description Cupos que quedan en ese horario. 0 significa lleno: el horario se devuelve igual para
             *     que el front lo pinte en gris, como hace el prototipo.
             * @example 1
             */
            cuposDisponibles: number;
        };
        DisponibilidadDto: {
            /** @example 2026-10-05 */
            fecha: string;
            data: components["schemas"]["SlotDto"][];
        };
        CreateReservaDto: {
            /**
             * @description Formato YYYY-MM-DD.
             * @example 2026-10-05
             */
            fecha: string;
            /**
             * @description Formato HH:mm, de la grilla del centro.
             * @example 09:45
             */
            hora: string;
            /**
             * @example efectivo
             * @enum {string}
             */
            metodoPago: "efectivo" | "mercadopago";
            servicioId: string;
            /** @description Un solo campo, como el formulario del prototipo. */
            clienteNombre: string;
            /** Format: email */
            clienteEmail: string;
            clienteTelefono: string;
            notas?: string;
        };
        ReservaDto: {
            /** @example 2026-10-05 */
            fecha: string;
            /** @example 09:45 */
            horaInicio: string;
            /** @example 10:30 */
            horaFin: string;
            /**
             * @description `pendiente`, `confirmada` o `cancelada`.
             * @example confirmada
             */
            estado: string;
            /**
             * @description `efectivo` o `mercadopago`.
             * @example efectivo
             */
            metodoPago: string;
            /**
             * @description Sena congelada al momento de reservar, en centavos.
             * @example 540000
             */
            senaCentavos: number;
            id: string;
            clienteNombre: string;
            clienteEmail: string;
            clienteTelefono: string;
            notas: string | null;
            servicioId: string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateReservaDto: {
            /**
             * @description Nuevo estado. Transiciones validas: pendiente -> confirmada | cancelada,
             *     confirmada -> cancelada. `cancelada` es terminal.
             * @example cancelada
             * @enum {string}
             */
            estado: "confirmada" | "cancelada";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SesionesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearSesionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionDto"];
                };
            };
            /** @description Credenciales incorrectas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El centro no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    ServiciosController_findAll: {
        parameters: {
            query: {
                /**
                 * @description Filtra por estado. El front del cliente pide `activo=true`; el ABM no manda nada y ve
                 *     todo. Es un filtro comun y no un flag de autorizacion: un parametro que cambia el nivel
                 *     de acceso de una ruta publica es lo que se rompe en el segundo refactor.
                 */
                activo?: boolean;
                /** @description Cuantos elementos devolver como maximo en esta pagina. */
                limit: number;
                /** @description El nextCursor que devolvio la pagina anterior. Es opaco: mandalo tal cual. */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Una pagina de resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPageDto"] & {
                        data?: components["schemas"]["ServicioDto"][];
                    };
                };
            };
            /**
             * @description El centro no existe o esta inactivo.
             *
             *     El centro o el tratamiento no existe.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    ServiciosController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServicioDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicioDto"];
                };
            };
            /** @description Datos invalidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El token es de otro centro. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /**
             * @description El centro no existe o esta inactivo.
             *
             *     El centro o el tratamiento no existe.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description Ya hay un tratamiento con ese nombre. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    ServiciosController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                servicioId: string;
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicioDto"];
                };
            };
            /**
             * @description El centro no existe o esta inactivo.
             *
             *     El centro o el tratamiento no existe.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    ServiciosController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                servicioId: string;
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServicioDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicioDto"];
                };
            };
            /** @description Datos invalidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El token es de otro centro. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /**
             * @description El centro no existe o esta inactivo.
             *
             *     El centro o el tratamiento no existe.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description Ya hay un tratamiento con ese nombre. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    VentanasAtencionController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VentanasAtencionDto"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El token es de otro centro. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El centro no existe o esta inactivo. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    VentanasAtencionController_replaceAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceVentanasDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VentanasAtencionDto"];
                };
            };
            /** @description Alguna franja es invalida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El token es de otro centro. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El centro no existe o esta inactivo. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description Hay franjas superpuestas. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    DisponibilidadController_find: {
        parameters: {
            query: {
                /** @description Formato YYYY-MM-DD. */
                fecha: string;
            };
            header?: never;
            path: {
                servicioId: string;
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisponibilidadDto"];
                };
            };
            /** @description Fecha invalida o muy lejana. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El centro o el tratamiento no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    ReservasController_findAll: {
        parameters: {
            query: {
                estado?: "pendiente" | "confirmada" | "cancelada";
                servicioId?: string;
                /** @description Desde esta fecha, inclusive. */
                desde?: string;
                /** @description Hasta esta fecha, inclusive. */
                hasta?: string;
                /** @description Cuantos elementos devolver como maximo en esta pagina. */
                limit: number;
                /** @description El nextCursor que devolvio la pagina anterior. Es opaco: mandalo tal cual. */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Una pagina de resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPageDto"] & {
                        data?: components["schemas"]["ReservaDto"][];
                    };
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El token es de otro centro. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El centro no existe o esta inactivo. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    ReservasController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaDto"];
                };
            };
            /** @description Datos invalidos o fecha muy lejana. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El centro o el tratamiento no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description Sin cupo, fuera de agenda, horario pasado o turno duplicado. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    ReservasController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservaId: string;
                /** @description Identificador del centro en la URL, por ejemplo `lo-de-lili`. */
                tenantSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReservaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaDto"];
                };
            };
            /** @description El estado pedido no existe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description El token es de otro centro. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description La reserva no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
            /** @description Esa transicion de estado no es valida. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
}
